"
This class represents package information for the GlorpCollectionTypeModels package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpCollectionTypeModelsPackage,
	#superclass : #Object,
	#category : #GlorpCollectionTypeModels
}

{ #category : #'VisualWorks metadata' }
GlorpCollectionTypeModelsPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
