"
This class represents package information for the GlorpExtensions package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpExtensionsPackage,
	#superclass : #Object,
	#category : #GlorpExtensions
}

{ #category : #'VisualWorks metadata' }
GlorpExtensionsPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
