"
This class represents package information for the GlorpMappings package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpMappingsPackage,
	#superclass : #Object,
	#category : #GlorpMappings
}

{ #category : #'VisualWorks metadata' }
GlorpMappingsPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
