"
This class represents package information for the GlorpDatabaseTypes package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpDatabaseTypesPackage,
	#superclass : #Object,
	#category : #GlorpDatabaseTypes
}

{ #category : #'VisualWorks metadata' }
GlorpDatabaseTypesPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
