"
This class represents package information for the GlorpDatabase package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpDatabasePackage,
	#superclass : #Object,
	#category : #GlorpDatabase
}

{ #category : #'VisualWorks metadata' }
GlorpDatabasePackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
