Class {
	#name : #ClassO,
	#superclass : #Object,
	#instVars : [
		'attrAClassO',
		'attrBClassO',
		'attrCClassO',
		'attrDClassO'
	],
	#category : #GlorpTestModels
}

{ #category : #'VisualWorks metadata' }
ClassO class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]

{ #category : #accessing }
ClassO >> attrAClassO [

	^attrAClassO
]

{ #category : #accessing }
ClassO >> attrAClassO: anObject [

	attrAClassO := anObject
]

{ #category : #accessing }
ClassO >> attrBClassO [

	^attrBClassO
]

{ #category : #accessing }
ClassO >> attrBClassO: anObject [

	attrBClassO := anObject
]

{ #category : #accessing }
ClassO >> attrCClassO [

	^attrCClassO
]

{ #category : #accessing }
ClassO >> attrCClassO: anObject [

	attrCClassO := anObject
]

{ #category : #accessing }
ClassO >> attrDClassO [

	^attrDClassO
]

{ #category : #accessing }
ClassO >> attrDClassO: anObject [

	attrDClassO := anObject
]
