Class {
	#name : #ClassL,
	#superclass : #Object,
	#instVars : [
		'attrAClassL',
		'attrBClassL',
		'attrCClassL',
		'attrDClassL'
	],
	#category : #GlorpTestModels
}

{ #category : #'VisualWorks metadata' }
ClassL class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]

{ #category : #accessing }
ClassL >> attrAClassL [

	^attrAClassL
]

{ #category : #accessing }
ClassL >> attrAClassL: anObject [

	attrAClassL := anObject
]

{ #category : #accessing }
ClassL >> attrBClassL [

	^attrBClassL
]

{ #category : #accessing }
ClassL >> attrBClassL: anObject [

	attrBClassL := anObject
]

{ #category : #accessing }
ClassL >> attrCClassL [

	^attrCClassL
]

{ #category : #accessing }
ClassL >> attrCClassL: anObject [

	attrCClassL := anObject
]

{ #category : #accessing }
ClassL >> attrDClassL [

	^attrDClassL
]

{ #category : #accessing }
ClassL >> attrDClassL: anObject [

	attrDClassL := anObject
]
