Extension { #name : #DefaultableThing }

{ #category : #'*GlorpDBTests' }
DefaultableThing >> boolean [
	^boolean
]

{ #category : #'*GlorpDBTests' }
DefaultableThing >> boolean: anObject [
	boolean := anObject
]

{ #category : #'*GlorpDBTests' }
DefaultableThing >> id [
	^id
]

{ #category : #'*GlorpDBTests' }
DefaultableThing >> id: anObject [
	id := anObject
]

{ #category : #'*GlorpDBTests' }
DefaultableThing >> integer [
	^integer
]

{ #category : #'*GlorpDBTests' }
DefaultableThing >> integer: anObject [
	integer := anObject
]
