"
This class represents package information for the GlorpDBTests package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpDBTestsPackage,
	#superclass : #Object,
	#category : #GlorpDBTests
}

{ #category : #'VisualWorks metadata' }
GlorpDBTestsPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
