"
This class represents package information for the GlorpDBTypeTests package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpDBTypeTestsPackage,
	#superclass : #Object,
	#category : #GlorpDBTypeTests
}

{ #category : #'VisualWorks metadata' }
GlorpDBTypeTestsPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
