"
This class represents package information for the GlorpExpressions package, for systems that don't have things like package properties to store things.  It is unused in VisualWorks.
"
Class {
	#name : #GlorpExpressionsPackage,
	#superclass : #Object,
	#category : #GlorpExpressions
}

{ #category : #'VisualWorks metadata' }
GlorpExpressionsPackage class >> visualWorksMetadata [

	^ #(
		'namespace' 'Glorp'
	)

]
